custom:
  server:
    port: 8088
  mysql:
    ip: 127.0.0.1
    port: 3306
    database: springboot-redis-example
    username: example
    password: password
  redis:
    ip: 127.0.0.1
    port: 6379
    password: password

server:
  port: ${custom.server.port}
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${custom.mysql.ip}:${custom.mysql.port}/${custom.mysql.database}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${custom.mysql.username}
    password: ${custom.mysql.password}
  # redis 配置
  redis:
    database: 0
    host: ${custom.redis.ip}
    port: ${custom.redis.port}
    password: ${custom.redis.password}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms

# mybatis-plus 配置
mybatis-plus:
  configuration:
    # 开启 mybatis 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl